### PR TITLE
add - project example

### PR DESCRIPTION
**Pull request by jesuspedge**
# Description

This PR adds the basic project example structure

- Add basic project example
- Add basic import of the package

### CODE REVIEW

**Comment by diegoveloper** [comment]
Don't forget to add the .gitignore file , you can copy that from this repo : https://github.com/gskinner/flutter_animate/blob/main/example/.gitignore

**Comment by monster555** [comment]
Do not include the `build` folder

**Review by victormanuelfrancodev — CHANGES_REQUESTED** [review]
In a PR (Pull Request), it is not well seen to send so many files for review; in this case, there are 326 files. The ideal approach is to break down the task and upload the files in parts. As Diego says, add the gitignore so that unnecessary files do not get mixed into the PR. It's a bit difficult to review so many files. I have to reject the PR until you add the .gitignore 🙇🏾

**Review by victormanuelfrancodev — APPROVED** [review]
Is it necessary to add example files for Linux, web, and Windows? For now, I will accept your PR. Thank you for adding the gitignore, it did reduce the number of files

**Review by diegoveloper — APPROVED** [review]
Lgtm

**Pull request merged**
