### PR TITLE
Improve example project

### PR DESCRIPTION
**Pull request by jesuspedge**
## Description

This PR added 3  new examples to the main examples project and horizontal and vertical view.

## Current examples

- [x] Inspiration example.
- [x] Books example.
- [x] Pokemons example.
- [x] Separated example.
- [x] Build Example.

## Video

https://github.com/the-d-velopers/animated_book_list/assets/74924269/d4136704-f45b-4dab-8a0d-eb57a9d75c3b

### CODE REVIEW

**Comment by diegoveloper** [comment]
can you attach a video about how this looks?

**Comment by jesuspedge** [comment]
Video added!

**Review by diegoveloper — APPROVED** [review]
It looks great! Awesome job

**Review by ricardogottheil — APPROVED** [review]

**Review by victormanuelfrancodev — APPROVED** [review]
Nice job!

**Pull request merged**
